# GoReleaser configuration for gofs
# See: https://goreleaser.com

version: 2

project_name: gofs

before:
  hooks:
    - go mod tidy

builds:
  - id: gofs
    main: ./cmd/gofs
    binary: gofs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - Merge pull request
      - Merge branch

dockers_v2:
  - id: gofs
    dockerfile: Dockerfile.goreleaser
    ids:
      - gofs
    platforms:
      - linux/amd64
      - linux/arm64
    images:
      - "ghcr.io/samzong/{{ .ProjectName }}"
      - "samzong/{{ .ProjectName }}"
    tags:
      - "{{ .Tag }}"
      - "latest"
    flags:
      - "--pull"
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "https://github.com/samzong/{{ .ProjectName }}"
      org.opencontainers.image.description: "Simple file server written in Go"

release:
  github:
    owner: "samzong"
    name: "{{ .ProjectName }}"
  draft: false
  prerelease: auto
  mode: replace
  replace_existing_artifacts: true
  header: |
    ## What's Changed

    ### Docker Images

    Multi-architecture Docker images are available on GitHub Container Registry and Docker Hub:

    ```bash
    # Pull from GitHub Container Registry
    docker pull ghcr.io/samzong/{{ .ProjectName }}:{{ .Tag }}
    docker pull ghcr.io/samzong/{{ .ProjectName }}:latest

    # Pull from Docker Hub
    docker pull samzong/{{ .ProjectName }}:{{ .Tag }}
    docker pull samzong/{{ .ProjectName }}:latest

    # Run the container
    docker run -p 8000:8000 -v $(pwd):/data:ro samzong/{{ .ProjectName }}:{{ .Tag }}
    ```

    Supported architectures: `linux/amd64`, `linux/arm64`
  footer: |
    **Full Changelog**: https://github.com/samzong/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - name: gofs
    repository:
      owner: "samzong"
      name: homebrew-tap
      branch: "update-gofs-{{ .Tag }}"
      pull_request:
        enabled: true
        base:
          branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/samzong/{{ .ProjectName }}"
    description: "A lightweight, fast HTTP file server written in Go"
    license: "MIT"
    url_template: "https://github.com/samzong/{{ .ProjectName }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: github-actions[bot]
      email: 41898282+github-actions[bot]@users.noreply.github.com
    test: |
      system "#{bin}/gofs", "--version"
    install: |
      bin.install "gofs"
    skip_upload: false
